### ISSUE TITLE
Problem GeoJSON polygons generated with function bboxToPolygon (bbox)

### ISSUE THREAD

**Issue by inteliti** [luscus/geojson.lib#2]
Hello,

Thankyou for your work, i am dealing with your geojson.lib.routeboxer project. But i had a problem with GeoJSON genarated from bboxToPolygon function. In some GeoJSON sintax tester like http://geojson.io/ i get the error that said "the polygon must end with the start point", so add this line to your tool.js:64 code:

function bboxToPolygon (bbox) {

  var polygon = {
    type: 'Polygon',
    bbox: bbox,
    coordinates: [
      [[bbox[0], bbox[1]],
        [bbox[0], bbox[3]],
        [bbox[2], bbox[3]],
        [bbox[2], bbox[1]],
    [bbox[0], bbox[1]]] //a polygon must ends in its first point
    ]
  };

  return setPrecison(polygon, 4);
}

I hope it help you and some others...

**Comment by luscus** [comment]
sorry, I didn't received a notice about your issue.
Good finding, I will fix this this evening.

**Comment by luscus** [comment]
Issue closed, thanks a lot again
I which I had more time for this Lib
